//app
export const GET_INFO_TEXT_PROCESS = 'GET_INFO_TEXT_PROCESS';
export const GET_INFO_TEXT_SUCCESS = 'GET_INFO_TEXT_SUCCESS';
export const GET_INFO_TEXT_ERROR = 'GET_INFO_TEXT_ERROR';

export const GET_INFO_AUTHORS_PROCESS = 'GET_INFO_AUTHORS_PROCESS';
export const GET_INFO_AUTHORS_SUCCESS = 'GET_INFO_AUTHORS_SUCCESS';
export const GET_INFO_AUTHORS_ERROR = 'GET_INFO_AUTHORS_ERROR';

export const GET_INFO_GENRES_PROCESS = 'GET_INFO_GENRES_PROCESS';
export const GET_INFO_GENRES_SUCCESS = 'GET_INFO_GENRES_SUCCESS';
export const GET_INFO_GENRES_ERROR = 'GET_INFO_GENRES_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAN_ALERT = 'CLEAN_ALERT';


